### ISSUE TITLE
Добавить базовый шаблон для всего приложения

### ISSUE THREAD

**Issue by ram0973** [SLabuzov/twitter-client-app#6]
Просьба показать, как лучше всего создать базовый шаблон для всего приложения, который выводится на всех страницах сайта.
Конкретная страница выводится например в {props.children}
Типа такого, или более правильный вариант:
```
const BaseLayout = (props) => {
  return (
    <>
      <Container maxW={"container.lg"}>
        <NavigationBar/>
        {props.children}
        <Footer/>
      </Container>
    </>
  )
}
```
Вот так вроде работает, но у меня при таком шаблоне не работают теги Link на кнопках в NavigationBar

**Comment by SLabuzov** [comment]
Если правильно понял суть проблемы, Вам нужно использовать <Outlet/> из react-router-dom
https://reactrouter.com/en/main/start/tutorial#nested-routes

**Comment by ram0973** [comment]
Сделал так:
https://github.com/ram0973/spring-react-site/blob/main/react/src/main.tsx
Отдельные страницу для админки и фронта
