### ISSUE TITLE
Выделить запросы данных в отдельный пакет services по аналогии со Спрингом

### ISSUE THREAD

**Issue by ram0973** [SLabuzov/twitter-client-app#7]
Есть ли смысл отделить запросы данных в отдельный пакет?:
services - запросы данных через axios
Также интерейсы в models.
Так вроде удобнее по аналогии со спрингом.
Если это ломает текущую логику пакетов, то не надо

**Comment by SLabuzov** [comment]
в этом есть смысл :slightly_smiling_face: 
только конкретная реализация должна быть максимально близко к ее использованию (т.е. в соответствующем пакете feature)

**Comment by ram0973** [comment]
Несущественно, закрываю
