### ISSUE TITLE
Выводить сообщения в Toast

### ISSUE THREAD

**Issue by ram0973** [SLabuzov/twitter-client-app#8]
Просьба показать, как можно выводить информационные сообщения при получении данных например в 
Chakra Toast. Например, запись уcпешно удалена. Или Ошибка: не найдена запись с таким id.  

Причем загвоздка в том, что компоненты Toast дожны быть общими для исключения дублирования кода, и вызываться из других компонентов программно. Например так:
```
import {createStandaloneToast} from '@chakra-ui/react'
const {ToastContainer, toast} = createStandaloneToast()
```

Или всё-таки у каждого компонента (пользователи, твиты) есть свои Toast? Тогда они выводятся с помощью css тегов absolute?

**Comment by SLabuzov** [comment]
Например, это все можно завернуть в интерсептеры axios. Но тогда придется чуть подкрутить Response объекты возвращаемые спрингом

**Comment by ram0973** [comment]
Сделал проще, через хук useToast
